[Settings.Debugging]
bEnableDebugLogs = true

[Settings.Toggles]
bUse24HourFormat = true
bShowRealTime = false
bShowGameTime = true

[Settings.Positions]
fPositionX = 800.0
fPositionY = 10.0

[Settings.Scale]
fClockScale = 1.0

[Settings.Misc]
fClockAlpha = 1.0
uClockColor = "#4cbb17"

[Settings.Fonts]
sFont = "Jost-Regular.ttf"
iFontSize = 32

[Settings.Hotkeys]
sEditorToggleKey = "F11"
sClockToggleKey = "F10"