[Settings.Debugging]
# Enable or disable debug logs
bEnableDebugLogs = true 

[Settings.Toggles]
# Show or hide the clock
bShowClock = true 
# Use 24-hour format for the clock
bUse24HourFormat = false

[Settings.Positions]
# X position of the clock on the screen. 0 is left edge
fPositionX = 800.0 
# Y position of the clock on the screen. 0 is top edge
fPositionY = 5.0 

[Settings.Scale]
# Scale of the clock. 1.0 is normal size, 2.0 is double size, etc.
fClockScale = 1.0 

[Settings.Misc]
# Opacity of the clock. 0.0 is fully transparent, 1.0 is fully opaque
fClockAlpha = 1.0 
# Color of the clock in hex format with alpha accepts 0xRRGGBB, 0xRRGGBBAA, or #RRGGBB, #RRGGBBAA
uClockColor = "#4cbb17" 

[Settings.Fonts]
# Font file for the clock. File Path is Interface/ImGuiIcons/Fonts/
sFont = "Jost-Regular.ttf" 
# Font size for the clock
iFontSize = 32 

[Settings.Hotkeys]
sEditorToggleKey = "F11"

